version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - touch hifile
  build:
    commands:
      - ls -la .
#      - docker build --tag=584643220196.dkr.ecr.us-east-2.amazonaws.com/thisara-test-backend:V1.0 .
#      - $(aws ecr get-login --region us-east-2 --no-include-email)
  post_build:
    commands:
      - echo "Hi"
#      - docker push 584643220196.dkr.ecr.us-east-2.amazonaws.com/thisara-test-backend:V1.0
