version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 8

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ls -la .
      - npm run build
      - docker build --tag=584643220196.dkr.ecr.us-east-2.amazonaws.com/thisara-test-backend:V1.0 .
      - $(aws ecr get-login --region us-east-2 --no-include-email)
  post_build:
    commands:
      - docker push 584643220196.dkr.ecr.us-east-2.amazonaws.com/thisara-test-backend:V1.0
